const actions = {
  USER_REGISTRATION: "USER_REGISTRATION",
  USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: "USER_REGISTRATION_FAILURE",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",
  SET_AUTHENTICATION: "SET_AUTHENTICATION",
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  USER_REGISTRATION: "USER_REGISTRATION",
  USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: "USER_REGISTRATION_FAILURE",

  CLEAR_AUTH: "CLEAR_AUTH",
};

export default actions;